// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as models$0 from "../../../../../cosmicmail/internal/models/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "mail:messages-updated": models$0.MessagesUpdatedEvent;
            "mail:new-messages": models$0.NewMessagesEvent;
            "mail:sync-state": models$0.SyncStateEvent;
            "omarchy:theme-changed": models$0.OmarchyTheme;
        }
    }
}
