// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service bound to the frontend. Every method here is a command
 * in docs/ARCHITECTURE.md; `wails3 generate bindings` turns them into the
 * typed TypeScript in frontend/bindings. Methods are intentionally thin:
 * they validate inputs, delegate to the internal packages, and return plain
 * errors, which reach the frontend as rejected promises carrying the message.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * AddImapAccount adds a plain IMAP account, validating credentials by
 * connecting first.
 */
export function AddImapAccount(input: models$0.ImapAccountInput): $CancellablePromise<models$0.Account> {
    return $Call.ByID(2365024458, input);
}

/**
 * ArchiveMessage moves a message to the account's archive-role folder.
 */
export function ArchiveMessage(messageID: number): $CancellablePromise<void> {
    return $Call.ByID(1916347740, messageID);
}

/**
 * DeleteMessage deletes a message: permanently when already in trash,
 * otherwise it moves it to trash.
 */
export function DeleteMessage(messageID: number): $CancellablePromise<void> {
    return $Call.ByID(4055978473, messageID);
}

/**
 * DiscoverAccountConfig discovers IMAP/SMTP settings for an email address.
 * It errors only on an invalid address; a "not found" result falls through to
 * a heuristic guess with confident: false.
 */
export function DiscoverAccountConfig(email: string): $CancellablePromise<models$0.DiscoveredConfig> {
    return $Call.ByID(2047522331, email);
}

/**
 * GetMessageBody returns a message body, fetching from the server (and
 * caching) if not present.
 */
export function GetMessageBody(messageID: number): $CancellablePromise<models$0.MessageBody> {
    return $Call.ByID(125200066, messageID);
}

/**
 * GetSettings reads the global application settings. It never errors: a
 * missing or malformed settings file yields defaults.
 */
export function GetSettings(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(2554697378);
}

/**
 * GetTheme reads the active omarchy theme.
 */
export function GetTheme(): $CancellablePromise<models$0.OmarchyTheme> {
    return $Call.ByID(1815524992);
}

/**
 * ListAccounts lists all configured accounts (public projection).
 */
export function ListAccounts(): $CancellablePromise<models$0.Account[] | null> {
    return $Call.ByID(2919187697);
}

/**
 * ListFolders lists an account's folders.
 */
export function ListFolders(accountID: string): $CancellablePromise<models$0.Folder[] | null> {
    return $Call.ByID(243286990, accountID);
}

/**
 * ListMessages pages messages for a folder, newest first.
 */
export function ListMessages(folderID: number, offset: number, limit: number): $CancellablePromise<models$0.MessageSummary[] | null> {
    return $Call.ByID(2939394281, folderID, offset, limit);
}

/**
 * ListShipmentsForMessage lists shipments detected in a message's cached
 * body (empty until the body has been fetched, or if none were detected).
 */
export function ListShipmentsForMessage(messageID: number): $CancellablePromise<models$0.Shipment[] | null> {
    return $Call.ByID(2074113850, messageID);
}

/**
 * ListUnifiedMessages pages messages across all inbox folders of all
 * accounts, newest first.
 */
export function ListUnifiedMessages(offset: number, limit: number): $CancellablePromise<models$0.MessageSummary[] | null> {
    return $Call.ByID(825905281, offset, limit);
}

/**
 * MarkFlagged sets/clears \Flagged on the server and in the local cache.
 */
export function MarkFlagged(messageID: number, flagged: boolean): $CancellablePromise<void> {
    return $Call.ByID(3452885910, messageID, flagged);
}

/**
 * MarkRead sets/clears the seen flag on the server and in the local cache.
 * 
 * On a Gmail account, the same physical message is exposed under multiple
 * folders (labels); after the primary update, other cached copies sharing
 * the same RFC 5322 Message-ID within the account are updated locally too.
 */
export function MarkRead(messageID: number, seen: boolean): $CancellablePromise<void> {
    return $Call.ByID(104109500, messageID, seen);
}

/**
 * MoveMessage moves a message to another folder of the same account.
 */
export function MoveMessage(messageID: number, targetFolderID: number): $CancellablePromise<void> {
    return $Call.ByID(2984231899, messageID, targetFolderID);
}

/**
 * ReauthGmailAccount re-runs the interactive Gmail OAuth consent for an
 * existing account, in place: the account, its folders and cached mail are
 * untouched — only the keyring refresh token is replaced. Errors without
 * storing anything if the completed consent belongs to a different Google
 * account than the one being reconnected.
 */
export function ReauthGmailAccount(accountID: string): $CancellablePromise<models$0.Account> {
    return $Call.ByID(1424749443, accountID);
}

/**
 * RemoveAccount removes an account, its cached data, secrets, and running
 * sync task.
 */
export function RemoveAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(205763644, accountID);
}

/**
 * SaveAttachment saves an attachment to the user's downloads directory and
 * returns its path. Raw RFC822 is not cached, so this refetches the message
 * (BODY.PEEK[], non-marking), re-parses, extracts the part by its stable
 * index, and writes it under a sanitised, collision-suffixed filename.
 */
export function SaveAttachment(attachmentID: number): $CancellablePromise<string> {
    return $Call.ByID(2182723789, attachmentID);
}

/**
 * SearchMessages is a relevance-ranked full-text search over the local
 * cache. A nil accountID spans every account; otherwise it is scoped to that
 * account. Server-side IMAP SEARCH is not involved.
 */
export function SearchMessages(query: string, accountID: string | null, offset: number, limit: number): $CancellablePromise<models$0.MessageSummary[] | null> {
    return $Call.ByID(3203246577, query, accountID, offset, limit);
}

/**
 * SendMessage submits a plain-text message through the selected account's
 * SMTP server.
 */
export function SendMessage(input: models$0.SendMessageInput): $CancellablePromise<void> {
    return $Call.ByID(1496882310, input);
}

/**
 * StartGmailOauth runs the interactive Gmail OAuth flow and registers the
 * account.
 */
export function StartGmailOauth(): $CancellablePromise<models$0.Account> {
    return $Call.ByID(1980394118);
}

/**
 * SyncAccount triggers a background re-sync for an account.
 */
export function SyncAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(1238325453, accountID);
}

/**
 * SyncFolder triggers a background re-sync for the account that owns a
 * folder.
 */
export function SyncFolder(folderID: number): $CancellablePromise<void> {
    return $Call.ByID(1504012682, folderID);
}

/**
 * TestNotification sends a sample notification.
 */
export function TestNotification(): $CancellablePromise<void> {
    return $Call.ByID(2373108510);
}

/**
 * UpdateSettings persists the global application settings and returns the
 * stored value.
 */
export function UpdateSettings(s: models$0.Settings): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(2894041249, s);
}
