// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account is the public projection of a configured account (no secrets, no
 * connection details).
 */
export interface Account {
    "id": string;
    "email": string;
    "displayName": string;
    "kind": AccountKind;
}

/**
 * AccountKind selects the auth mechanism used for IMAP/SMTP.
 */
export enum AccountKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AccountKindImap = "imap",
    AccountKindGmail = "gmail",
};

/**
 * AttachmentInfo is attachment metadata shown in the reader (no bytes).
 */
export interface AttachmentInfo {
    "id": number;
    "filename": string;
    "mimeType": string;
    "sizeBytes": number;
    "isInline": boolean;
}

/**
 * DiscoveredConfig is the settings-discovery result.
 */
export interface DiscoveredConfig {
    "kind": AccountKind;
    "imapHost": string;
    "imapPort": number;
    "smtpHost": string;
    "smtpPort": number;
    "username": string;
    "source": DiscoverySource;
    "confident": boolean;
}

/**
 * DiscoverySource says where a DiscoveredConfig came from.
 */
export enum DiscoverySource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceAutoconfig = "autoconfig",
    SourceIspdb = "ispdb",
    SourceMx = "mx",
    SourceSrv = "srv",
    SourceGuess = "guess",
};

/**
 * Folder is a mail folder projection.
 */
export interface Folder {
    "id": number;
    "accountId": string;
    "name": string;
    "role": string;
    "unreadCount": number;
    "totalCount": number;
}

/**
 * ImapAccountInput is the input for adding a plain IMAP account.
 */
export interface ImapAccountInput {
    "email": string;
    "displayName": string;
    "imapHost": string;
    "imapPort": number;
    "smtpHost": string;
    "smtpPort": number;
    "username": string;
    "password": string;
}

/**
 * MessageBody is a message body plus recipient lists and attachment metadata.
 */
export interface MessageBody {
    "id": number;
    "html": string | null;
    "text": string | null;
    "toAddrs": string[] | null;
    "ccAddrs": string[] | null;
    "attachments": AttachmentInfo[] | null;
}

/**
 * MessageSummary is one row of the message list.
 */
export interface MessageSummary {
    "id": number;
    "accountId": string;
    "folderId": number;
    "uid": number;
    "subject": string;
    "fromName": string;
    "fromAddr": string;
    "date": string;
    "snippet": string;
    "seen": boolean;
    "flagged": boolean;
    "hasAttachments": boolean;
}

/**
 * MessagesUpdatedEvent is the payload of `mail:messages-updated`.
 */
export interface MessagesUpdatedEvent {
    "folderId": number;
}

/**
 * NewMessagesEvent is the payload of `mail:new-messages`.
 */
export interface NewMessagesEvent {
    "accountId": string;
    "folderId": number;
    "messages": MessageSummary[] | null;
}

/**
 * OmarchyTheme is the active omarchy theme's colors.
 */
export interface OmarchyTheme {
    "name": string;
    "accent": string;
    "foreground": string;
    "background": string;
    "cursor": string;
    "selectionForeground": string;
    "selectionBackground": string;
    "palette": string[] | null;
}

/**
 * SendMessageInput is a plain-text message submitted through an account's
 * SMTP server.
 */
export interface SendMessageInput {
    "accountId": string;
    "toAddrs": string[] | null;
    "ccAddrs": string[] | null;
    "bccAddrs": string[] | null;
    "subject": string;
    "bodyText": string;
    "replyToMessageId": number | null;
}

/**
 * Settings holds the global, non-secret preferences.
 */
export interface Settings {
    "alwaysDownloadRemoteImages": boolean;
}

/**
 * Shipment is a shipment detected in a message body by local heuristics.
 */
export interface Shipment {
    "id": number;
    "carrier": string;
    "trackingNumber": string | null;
    "trackingUrl": string | null;
    "orderId": string | null;
    "detectedAt": string;
}

/**
 * SyncState is the per-account sync state reported to the frontend.
 */
export enum SyncState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SyncIdle = "idle",
    SyncSyncing = "syncing",
    SyncError = "error",
};

/**
 * SyncStateEvent is the payload of `mail:sync-state`.
 */
export interface SyncStateEvent {
    "accountId": string;
    "state": SyncState;
    "error": string | null;

    /**
     * True only when the failure is classified AuthExpired (dead Gmail
     * credentials): retrying cannot help and the UI should offer Reconnect.
     */
    "needsReauth": boolean;
}
